# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_d10d_phy_0_hssio_rx.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_d10d_phy_0_hssio_rx.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_d10d_phy_0_hssio_rx_ooc.xdc

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_d10d_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_d10d_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_d10d_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_d10d_phy_0_hssio_rx.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_d10d_phy_0_hssio_rx.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_d10d_phy_0_hssio_rx_ooc.xdc

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_d10d_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_d10d_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zw/share/ultra96/ultra96_design/ultra96_design/ultra96_design.srcs/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_d10d_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
